### ISSUE TITLE
Problem when publishing topics for lights and steering at the same time

### ISSUE THREAD

**Issue by mnegretev** [AutoModelCar/model_car#1]
We find a problem when we try to set values both for lights and steering. Consider the next simple code:

ros::Rate loop(1);
while(ros::ok())
{
    //Some stuff for setting the desired messages
   msgSteering.data = 180;
   msgLights.data = "pa";
   pubLights.publish(msgLights);
   pubSteering.publish(msgSteering);
}

Frontal tires should keep heading to the left (180), nevertheless, they return to 0 randomly (apparently). If we comment the line "pubLights.publish()", the steering starts to work perfectly. Also, if we publish only the topic for lights, it works well. The problem comes when we publish both topics.

**Comment by AutoModelCar** [comment]
ok, I will test it on Monday.

**Comment by AutoModelCar** [comment]
I found the problem. 
Please update the your catkin_ws and arduino code "main.ino" in your model car.

git clone https://github.com/AutoModelCar/model_car/tree/master/catkin_ws
scp -r catkin_ws root@192.168.1.199

using arudino software please update the arduino code:
https://github.com/AutoModelCar/auto_arduino_nano/tree/master/main
