### ISSUE TITLE
where I can find the node posting on this topic

### ISSUE THREAD

**Issue by rafacastalla** [AutoModelCar/model_car#15]
https://github.com/AutoModelCar/model_car/blob/6a34eb00a99a62cc76ef97bedd5fdf0d3809ad2c/catkin_ws/src/control/src/control_node.cpp#L41

Thanks!

**Comment by AutoModelCar** [comment]
You should write your own line detection, but a student wrote a node which needs calibration, and could be a good start:
https://github.com/AutoModelCar/catkin_ws_user/tree/master/src/fu_line_detection
There is also a wiki for:
https://github.com/AutoModelCar/AutoModelCarWiki/wiki/FU-line-detection
