### ISSUE TITLE
Missing frame_id for the published images in FubCameraStaticCalibration.cpp

### ISSUE THREAD

**Issue by sayali-purdue** [AutoModelCar/model_car#16]
The header of an image variable of type sensor_msgs::Image should contain the optical frame of the camera, as per the following ROS document:
http://docs.ros.org/kinetic/api/sensor_msgs/html/msg/Image.html

However, the images published by the node 'catkin_ws/src/fub_camera_calibration/src/FubCameraStaticCalibration.cpp'  at lines #223 and #237 do not contain this frame information (snapshots are below)

<img width="681" alt="Screen Shot 2020-04-24 at 11 29 19 PM" src="https://user-images.githubusercontent.com/14244089/80270138-9103bb00-8683-11ea-99c7-96708b80d538.png">
<img width="616" alt="Screen Shot 2020-04-24 at 11 29 35 PM" src="https://user-images.githubusercontent.com/14244089/80270140-97923280-8683-11ea-8ac6-1a2ab89d361b.png">
Can you please explain why the frame information is not specified in the images?

Thank you!

**Comment by AutoModelCar** [comment]
Because we don't use the frame so it doesn't matter to initialize it.
It is a standalone node.

**Comment by sayali-purdue** [comment]
Thanks for your reply. I am doing a static review of the code. I would really appreciate if you could provide me a couple of details:

1. will this node be useful for tasks such as SLAM or visual odometry?
2. as a developer of this code, do you think this frame_id info will be useful to others, who want to use this node?

Thanks!

**Comment by AutoModelCar** [comment]
This code has a specific setup to calibrate the camera. You should put 6 white points (in 2 columns, 3 rows) in front of the car to find the extrinsic calibration. So no, you can not use the node easily in another node.

I updated the wiki, I hope it helps: 
[Wiki to camera calibration](https://github.com/AutoModelCar/AutoModelCarWiki/wiki/Camera-Calibration)
