### ISSUE TITLE
Error compiling after updating catkin_ws

### ISSUE THREAD

**Issue by hector-sab** [AutoModelCar/model_car#2]
After updating catkin_ws folder, some packages where not building. I deleted the catkin_ws folder in the odroid and copied it again to it, but now non of your packages are building. Is there something else that I have to do besides to copy the catkin_ws to make it work?

This is the log when I try to compile 

Profile:                     default
Extending:          [cached] /root/catkin_ws_user/odroid-devel:/opt/ros/indigo://opt/ros/indigo
Workspace:                   /root/catkin_ws
-----------------------------------------------------------------------------------------------
Source Space:       [exists] /root/catkin_ws/src
Log Space:          [exists] /root/catkin_ws/logs
Build Space:        [exists] /root/catkin_ws/build
Devel Space:        [exists] /root/catkin_ws/devel
Install Space:      [unused] /root/catkin_ws/install
DESTDIR:            [unused] None
-----------------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------------------------------------------
[build] Found '18' packages in 0.0 seconds.                                                                                                   
[build] Package table is up to date.                                                                                                          
Starting  >>> auto_stop                                                                                                                       
Starting  >>> control                                                                                                                         
Starting  >>> cv_bridge                                                                                                                       
Starting  >>> manual_control                                                                                                                  
Starting  >>> odometry                                                                                                                        
Starting  >>> random_movement                                                                                                                 
Starting  >>> rplidar_ros                                                                                                                     
Starting  >>> serial                                                                                                                          
______________________________________________________________________________________________________________________________________________
Errors     << manual_control:symlink /root/catkin_ws/logs/manual_control/build.symlink.001.log                                                
Stage `symlink` failed with arguments:
  package: {'package_format': 1, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [], 'name': 'manual_control', 'filename': '/root/catkin_ws/src/manual_control/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0xb65c2ab0>], 'version': '0.0.0', 'build_depends': [], 'urls': [], 'authors': [], 'licenses': ['ZARGOL'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb65b8f90>], 'conflicts': [], 'description': u'Manual control using android App'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/manual_control
  prebuild: False
  package_path: manual_control
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/manual_control
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 24: ordinal not in range(128)

..............................................................................................................................................
Failed     << manual_control:symlink                [ Exited with code 3 ]                                                                    
Failed    <<< manual_control                        [ 2.2 seconds ]                                                                           
Abandoned <<< usb_cam                               [ Unrelated job failed ]                                                                  
Abandoned <<< cmvision                              [ Unrelated job failed ]                                                                  
Abandoned <<< detect_roof_rectangles                [ Unrelated job failed ]                                                                  
Abandoned <<< ip_mapping                            [ Unrelated job failed ]                                                                  
Abandoned <<< line_detection                        [ Unrelated job failed ]                                                                  
Abandoned <<< realsense_camera                      [ Unrelated job failed ]                                                                  
Abandoned <<< heading                               [ Unrelated job failed ]                                                                  
Abandoned <<< motor_communication                   [ Unrelated job failed ]                                                                  
Abandoned <<< send_steering_light                   [ Unrelated job failed ]                                                                  
Abandoned <<< visual_gps                            [ Unrelated job failed ]                                                                  
______________________________________________________________________________________________________________________________________________
Errors     << random_movement:symlink /root/catkin_ws/logs/random_movement/build.symlink.001.log                                              
Stage `symlink` failed with arguments:
  package: {'package_format': 1, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [<catkin_pkg.package.Dependency object at 0xb65b8750>, <catkin_pkg.package.Dependency object at 0xb65b8240>, <catkin_pkg.package.Dependency object at 0xb65b8270>, <catkin_pkg.package.Dependency object at 0xb65b8300>], 'name': 'random_movement', 'filename': '/root/catkin_ws/src/random_movement/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [<catkin_pkg.package.Dependency object at 0xb65b8b70>, <catkin_pkg.package.Dependency object at 0xb65b8990>, <catkin_pkg.package.Dependency object at 0xb65b8d20>, <catkin_pkg.package.Dependency object at 0xb65b8210>], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0xb65c27d0>], 'version': '0.0.0', 'build_depends': [<catkin_pkg.package.Dependency object at 0xb65b81b0>, <catkin_pkg.package.Dependency object at 0xb65b8f00>, <catkin_pkg.package.Dependency object at 0xb65b81e0>, <catkin_pkg.package.Dependency object at 0xb65b8f30>], 'urls': [], 'authors': [], 'licenses': ['TODO'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb65b8f60>], 'conflicts': [], 'description': u'The random_movement package'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/random_movement
  prebuild: False
  package_path: random_movement
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/random_movement
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9f in position 25: ordinal not in range(128)

..............................................................................................................................................
Failed     << random_movement:symlink               [ Exited with code 3 ]                                                                    
Failed    <<< random_movement                       [ 2.2 seconds ]                                                                           
______________________________________________________________________________________________________________________________________________
Errors     << rplidar_ros:symlink /root/catkin_ws/logs/rplidar_ros/build.symlink.001.log                                                      
Stage `symlink` failed with arguments:
  package: {'package_format': 1, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [<catkin_pkg.package.Dependency object at 0xb6670e40>, <catkin_pkg.package.Dependency object at 0xb6670e70>, <catkin_pkg.package.Dependency object at 0xb6670ea0>, <catkin_pkg.package.Dependency object at 0xb6670ed0>], 'name': 'rplidar_ros', 'filename': '/root/catkin_ws/src/rplidar_ros/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [<catkin_pkg.package.Dependency object at 0xb6670f00>, <catkin_pkg.package.Dependency object at 0xb6670f30>, <catkin_pkg.package.Dependency object at 0xb6670f60>, <catkin_pkg.package.Dependency object at 0xb6670e10>], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0xb66521b0>], 'version': '1.0.1', 'build_depends': [<catkin_pkg.package.Dependency object at 0xb6670810>, <catkin_pkg.package.Dependency object at 0xb6670870>, <catkin_pkg.package.Dependency object at 0xb66708d0>, <catkin_pkg.package.Dependency object at 0xb6670930>], 'urls': [], 'authors': [], 'licenses': ['BSD'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb6670990>], 'conflicts': [], 'description': u'The rplidar ros package'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/rplidar_ros
  prebuild: False
  package_path: rplidar_ros
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/rplidar_ros
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 25: ordinal not in range(128)

..............................................................................................................................................
Failed     << rplidar_ros:symlink                   [ Exited with code 3 ]                                                                    
Failed    <<< rplidar_ros                           [ 2.0 seconds ]                                                                           
______________________________________________________________________________________________________________________________________________
Errors     << auto_stop:symlink /root/catkin_ws/logs/auto_stop/build.symlink.001.log                                                          
Stage `symlink` failed with arguments:
  package: {'package_format': 1, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [<catkin_pkg.package.Dependency object at 0xb6670c30>, <catkin_pkg.package.Dependency object at 0xb6670c90>, <catkin_pkg.package.Dependency object at 0xb6670cf0>, <catkin_pkg.package.Dependency object at 0xb6670b10>], 'name': 'auto_stop', 'filename': '/root/catkin_ws/src/auto_stop/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [<catkin_pkg.package.Dependency object at 0xb6670b40>, <catkin_pkg.package.Dependency object at 0xb6670c00>, <catkin_pkg.package.Dependency object at 0xb6670c60>, <catkin_pkg.package.Dependency object at 0xb6670cc0>], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0xb6652a30>], 'version': '0.0.0', 'build_depends': [<catkin_pkg.package.Dependency object at 0xb6670a80>, <catkin_pkg.package.Dependency object at 0xb6670ab0>, <catkin_pkg.package.Dependency object at 0xb6670ae0>, <catkin_pkg.package.Dependency object at 0xb6670de0>], 'urls': [], 'authors': [], 'licenses': ['TODO'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb6670f90>], 'conflicts': [], 'description': u'The auto_stop package'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/auto_stop
  prebuild: False
  package_path: auto_stop
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/auto_stop
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9a in position 25: ordinal not in range(128)

..............................................................................................................................................
Failed     << auto_stop:symlink                     [ Exited with code 3 ]                                                                    
Failed    <<< auto_stop                             [ 1.5 seconds ]                                                                           
______________________________________________________________________________________________________________________________________________
Errors     << control:symlink /root/catkin_ws/logs/control/build.symlink.001.log                                                              
Stage `symlink` failed with arguments:
  package: {'package_format': 1, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [<catkin_pkg.package.Dependency object at 0xb6679f90>, <catkin_pkg.package.Dependency object at 0xb6679f30>], 'name': 'control', 'filename': '/root/catkin_ws/src/control/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [<catkin_pkg.package.Dependency object at 0xb6655930>, <catkin_pkg.package.Dependency object at 0xb6655e70>], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0xb65c2d10>], 'version': '0.0.0', 'build_depends': [<catkin_pkg.package.Dependency object at 0xb666d900>, <catkin_pkg.package.Dependency object at 0xb666d960>], 'urls': [], 'authors': [], 'licenses': ['ZARGOL'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb666d930>, <catkin_pkg.package.Dependency object at 0xb65b8780>], 'conflicts': [], 'description': u'PD controller for line following'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/control
  prebuild: False
  package_path: control
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/control
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 25: ordinal not in range(128)

..............................................................................................................................................
Failed     << control:symlink                       [ Exited with code 3 ]                                                                    
Failed    <<< control                               [ 1.2 seconds ]                                                                           
______________________________________________________________________________________________________________________________________________
Errors     << serial:symlink /root/catkin_ws/logs/serial/build.symlink.001.log                                                                
Stage `symlink` failed with arguments:
  package: {'package_format': 1, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [], 'name': 'serial', 'filename': '/root/catkin_ws/src/serial/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [], 'doc_depends': [], 'test_depends': [<catkin_pkg.package.Dependency object at 0xb6678330>], 'maintainers': [<catkin_pkg.package.Person object at 0xb65dce50>], 'version': '1.2.1', 'build_depends': [], 'urls': [<catkin_pkg.package.Url object at 0xb65dce90>, <catkin_pkg.package.Url object at 0xb65dced0>, <catkin_pkg.package.Url object at 0xb65dcf10>], 'authors': [<catkin_pkg.package.Person object at 0xb65dcf50>, <catkin_pkg.package.Person object at 0xb65dcf90>], 'licenses': ['MIT'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb6678030>], 'conflicts': [], 'description': u'Serial is a cross-platform, simple to use library for using serial ports on computers.  This library provides a C++, object oriented interface for interacting with RS-232 like devices on Linux and Windows.'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/serial
  prebuild: False
  package_path: serial
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/serial
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 24: ordinal not in range(128)

..............................................................................................................................................
Failed     << serial:symlink                        [ Exited with code 3 ]                                                                    
Failed    <<< serial                                [ 1.9 seconds ]                                                                           
______________________________________________________________________________________________________________________________________________
Errors     << odometry:symlink /root/catkin_ws/logs/odometry/build.symlink.001.log                                                            
Stage `symlink` failed with arguments:
  package: {'package_format': 1, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [<catkin_pkg.package.Dependency object at 0xb65c8750>, <catkin_pkg.package.Dependency object at 0xb65c8e40>, <catkin_pkg.package.Dependency object at 0xb65c8e70>, <catkin_pkg.package.Dependency object at 0xb65c81b0>], 'name': 'odometry', 'filename': '/root/catkin_ws/src/odometry/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [<catkin_pkg.package.Dependency object at 0xb65c8210>, <catkin_pkg.package.Dependency object at 0xb65c8270>, <catkin_pkg.package.Dependency object at 0xb65c82d0>, <catkin_pkg.package.Dependency object at 0xb65c8330>], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0xb667f770>], 'version': '0.2.3', 'build_depends': [<catkin_pkg.package.Dependency object at 0xb65c8390>, <catkin_pkg.package.Dependency object at 0xb65c83f0>, <catkin_pkg.package.Dependency object at 0xb65c8450>, <catkin_pkg.package.Dependency object at 0xb65c8180>], 'urls': [<catkin_pkg.package.Url object at 0xb667f5d0>, <catkin_pkg.package.Url object at 0xb667f510>, <catkin_pkg.package.Url object at 0xb667f550>], 'authors': [<catkin_pkg.package.Person object at 0xb667f590>], 'licenses': ['BSD'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb65c81e0>], 'conflicts': [], 'description': u'The odometry_publisher package'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/odometry
  prebuild: False
  package_path: odometry
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/odometry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 24: ordinal not in range(128)

..............................................................................................................................................
Failed     << odometry:symlink                      [ Exited with code 3 ]                                                                    
Failed    <<< odometry                              [ 1.7 seconds ]                                                                           
______________________________________________________________________________________________________________________________________________
Errors     << cv_bridge:symlink /root/catkin_ws/logs/cv_bridge/build.symlink.001.log                                                          
Stage `symlink` failed with arguments:
  package: {'package_format': 2, 'exports': [<catkin_pkg.package.Export object at 0xb65b97b0>], 'buildtool_export_depends': [], 'exec_depends': [<catkin_pkg.package.Dependency object at 0xb65c8240>, <catkin_pkg.package.Dependency object at 0xb65c82a0>, <catkin_pkg.package.Dependency object at 0xb65c8300>, <catkin_pkg.package.Dependency object at 0xb65c8360>], 'name': 'cv_bridge', 'filename': '/root/catkin_ws/src/cv_bridge/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [<catkin_pkg.package.Dependency object at 0xb65c83c0>], 'doc_depends': [<catkin_pkg.package.Dependency object at 0xb65c8420>], 'test_depends': [<catkin_pkg.package.Dependency object at 0xb65c8f30>], 'maintainers': [<catkin_pkg.package.Person object at 0xb667fbf0>], 'version': '1.12.0', 'build_depends': [<catkin_pkg.package.Dependency object at 0xb65c8f00>, <catkin_pkg.package.Dependency object at 0xb65c8ed0>, <catkin_pkg.package.Dependency object at 0xb65c87b0>, <catkin_pkg.package.Dependency object at 0xb65c8810>, <catkin_pkg.package.Dependency object at 0xb65c8870>], 'urls': [<catkin_pkg.package.Url object at 0xb667fbb0>, <catkin_pkg.package.Url object at 0xb667fdf0>, <catkin_pkg.package.Url object at 0xb667fe30>], 'authors': [<catkin_pkg.package.Person object at 0xb667fe70>, <catkin_pkg.package.Person object at 0xb667fd10>], 'licenses': ['BSD'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0xb65c88d0>], 'conflicts': [], 'description': u'This contains CvBridge, which converts between ROS\n    Image messages and OpenCV images.'}
  metadata_path: /root/catkin_ws/.catkin_tools/profiles/default
  devel_manifest_path: /root/catkin_ws/.catkin_tools/profiles/default/packages/cv_bridge
  prebuild: False
  package_path: cv_bridge
  dest_devel_path: /root/catkin_ws/devel
  source_devel_path: /root/catkin_ws/devel/.private/cv_bridge
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 146, in async_job
    event_queue))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x98 in position 56: ordinal not in range(128)

..............................................................................................................................................
Failed     << cv_bridge:symlink                     [ Exited with code 3 ]                                                                    
Failed    <<< cv_bridge                             [ 3.6 seconds ]                                                                           
[build] Summary: 0 of 18 packages succeeded.                                                                                                  
[build]   Ignored:   None.                                                                                                                    
[build]   Warnings:  None.                                                                                                                    
[build]   Abandoned: 10 packages were abandoned.                                                                                              
[build]   Failed:    8 packages failed.                                                                                                       
[build] Runtime: 5.1 seconds total.

**Comment by s3rgiux** [comment]
Did you find the error to compile the 1.1 workspace?

**Comment by ZahraBoroujeni** [comment]
When you copy the catkin_ws to the odroid, you do not need to compile it again! it is already compiled! just `source catkin_ws/devel/setup.bash`

**Comment by AutoModelCar** [comment]
close #2
