### ISSUE TITLE
About copy of files in Model Car.

### ISSUE THREAD

**Issue by arieleo2690** [AutoModelCar/model_car#3]
Hi, I just copied the whole files into memory car using copy.sh bash, however, after run set.sh and set2.sh, and rebuild the cw folder packages, the autostart.sh doesn't run anymore. It seems unrecognizable by the system now. How can I fix it?
I'm trying to make it executable at the boot of car, but doesn't work, only using bash autostart.sh into ssh session.

**Comment by arieleo2690** [comment]
It seems everything is well referenced, but I have some troubles for compile packages in version 1.1 of catkin_ws. What is the correct way for compiling? Using catkin build, or catkin_make?

**Comment by ZahraBoroujeni** [comment]
As I telled before you do not need to compile the catkin_ws folder, The packages already compiled and you can just use it by "source /root/catkin_ws/devel/setup.bash" and the "roslaunch ..."

**Comment by arieleo2690** [comment]
I just copied the entire arduino_nano folder into the model car. Is it necessary to compile into the car?

**Comment by arieleo2690** [comment]
It's done! Thanks.
