### ISSUE TITLE
Questions to odometry_publisher.cpp

### ISSUE THREAD

**Issue by neumann89** [AutoModelCar/model_car#4]
In the class, one of the students has two questions to odometry_publisher.cpp:
1. Line 22: Why the wheel radius is 0.31 meter? We measured 3.1cm = 0.031 meter
2. Line 45-48: Why values compared with 180 when head before is converted to rad (line 42)?

**Comment by SGSSGene** [comment]
1. It is a simple typo. It for sure needs to be corrected to 0.031 meter.

2. Also a bug. There are a few uncertainties here. Which should be fixed.

In general I believe @AutoModeCar is happy to review and accept PR on github for these issues.

**Comment by AutoModelCar** [comment]
fixed!

**Comment by SGSSGene** [comment]
2. Line 45-48 are still broken.

**Comment by SGSSGene** [comment]
No it seems to be fixed.

**Comment by SGSSGene** [comment]
Sorry for reopening this issue:
https://github.com/AutoModelCar/model_car/blob/b115e2ce0441969ed3766a59eba421d7489da789/catkin_ws/src/odometry/src/odometry_publisher.cpp#L22
Why did you change gear ratio from 6 to 5.5?
